import type { Metadata } from "next";
import { Providers } from "@/redux/providers";
import "@/assets/sass/global.scss";

export const metadata: Metadata = {
  title: "Soedarpo Informatika",
  description: "Generated by create next app",
};

import { AntdRegistry } from "@ant-design/nextjs-registry";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Providers>
        <AntdRegistry>{children}</AntdRegistry>
      </Providers>
    </section>
  );
}
