import type { Metadata } from "next";
import { Providers } from "@/redux/providers";
import "@/assets/sass/global.scss";
import { ZustandProvider } from "./components/providerZustand/provider";

export const metadata: Metadata = {
  title: "Soedarpo Informatika",
  description: "Generated by create next app",
};

import { AntdRegistry } from "@ant-design/nextjs-registry";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ZustandProvider>
          <Providers>
            <AntdRegistry>{children}</AntdRegistry>
          </Providers>
        </ZustandProvider>
      </body>
    </html>
  );
}
